server:
  port: 8080

spring:
    h2:
        console:
            enabled: true
            path: /console/

player:
    name: artur
    fullname: artur skrzydlo
    hostname: localhost
    port: ${server.port}
security:
  ignored: /**
